In [2]:
import torch
import numpy as np

### 初始化张量

#### 1.直接给出数据

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

#### 2.与numpy数组互相转换

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

#### 3.来自另一个张量

除非显式覆盖，否则新张量保留参数张量的属性（形状、数据类型）。

In [8]:
x_ones = torch.ones_like(x_data)    #保留x_data的属性
x_rand = torch.rand_like(x_data, dtype=float)    #覆盖x_data的属性
x_ones,x_rand

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.1475, 0.8983],
         [0.7593, 0.2849]], dtype=torch.float64))

#### 4.使用随机值或常量值

In [10]:
shape = (2,3)  #张量的维度的元组
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)
rand_tensor,ones_tensor,zero_tensor

(tensor([[0.0340, 0.0302, 0.9437],
         [0.9154, 0.2082, 0.8739]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### 张量的属性

#### 包括形状、数据类型以及存储它们的设备。

In [11]:
tensor = torch.rand(3,4)

print(f"张量形状/维度: {tensor.shape}")
print(f"张量数据类型: {tensor.dtype}")
print(f"存储设备: {tensor.device}")

张量形状/维度: torch.Size([3, 4])
张量数据类型: torch.float32
存储设备: cpu


### 张量的运算

超过 1200 个张量运算，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等。默认情况下在cpu创建，如果需要可以转换到gpu或者加速器上运行，使用.to方法

In [16]:
device =torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
device

device(type='cpu')

类似于numpy的切片索引

In [23]:
tensor = torch.tensor([[1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
print(tensor)
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:, 0]}")
print(f"最后一列: {tensor[..., -1]}")

tensor([[1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
第一行: tensor([1., 2., 3., 4.])
第一列: tensor([1., 1., 1., 1.])
最后一列: tensor([4., 1., 1., 1.])


按指定的维度连接张量

In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


张量乘法

In [31]:
y1 = tensor @ tensor.T  #张量与张量使用矩阵乘法
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor  #张量对应位置相乘
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[ 1.,  4.,  9., 16.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

单元素张量 使用item()将单元素张量转换成python数值

In [35]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

22.0 <class 'float'>


就地运算 将结果存储到操作数中的运算称为就地运算。它们用 _ 后缀表示。例如：x.copy_(y), x.t_() 将更改 x。

In [36]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 2., 3., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 7., 8., 9.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


### 与numpy的桥梁
他们会共享底层空间，修改一个会改变另一个的值

张量到numpy

In [40]:
n = tensor.numpy()
print(tensor)
print(n)

tensor([[6., 7., 8., 9.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
[[6. 7. 8. 9.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


修改张量时，numpy数组也会随之更改

In [41]:
tensor.add_(1)
print(n)

[[ 7.  8.  9. 10.]
 [ 7.  7.  7.  7.]
 [ 7.  7.  7.  7.]
 [ 7.  7.  7.  7.]]


NumPy 数组到张量


In [42]:
n = np.ones(5)
t = torch.from_numpy(n)

修改numpy数组时，张量也会随之更改

In [43]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])